on:
  pull_request:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 20.x
      - run: npm ci
      - run: npm test
      - run: npm run build
        if: github.ref == 'refs/heads/main'
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
        if: github.ref == 'refs/heads/main'
